local M = {}

local Client = require("grpctolua.Client")

-- descriptor set file is generated by:
--   protoc --descriptor_set_out=desc.pb a.proto b.proto
function M.load_descriptor_set_from_file(file_path)
    GrpcToLua.DescriptorSetLoader.LoadFromFile(file_path)
end

function M.load_descriptor_set_from_string(s)
    GrpcToLua.DescriptorSetLoader.LoadFromString(s)
end

function M.new_channel(target)
    return Grpc.Core.Channel(target, GrpcToLua.InsecureCredentials())
end

-- TODO: channel with credentials

function M.new_client(channel, service_name)
    return Client(channel, service_name)
end

return M